// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssignDriverToOrder(ctx context.Context, arg AssignDriverToOrderParams) error
	ConfirmOrderAcceptance(ctx context.Context, id uuid.UUID) error
	CreateDriver(ctx context.Context, arg CreateDriverParams) (CreateDriverRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	FindNearestDrivers(ctx context.Context, arg FindNearestDriversParams) ([]FindNearestDriversRow, error)
	GetDriver(ctx context.Context, id uuid.UUID) (GetDriverRow, error)
	GetDriverByEmail(ctx context.Context, email string) (GetDriverByEmailRow, error)
	ListDriversByFleet(ctx context.Context, fleetID uuid.UUID) ([]ListDriversByFleetRow, error)
	MarkOrderArrived(ctx context.Context, arg MarkOrderArrivedParams) (int64, error)
	MarkOrderDelivered(ctx context.Context, arg MarkOrderDeliveredParams) (int64, error)
	MarkOrderPickedUp(ctx context.Context, arg MarkOrderPickedUpParams) (int64, error)
	RejectOrderAssignment(ctx context.Context, arg RejectOrderAssignmentParams) error
	SetDriverStatus(ctx context.Context, arg SetDriverStatusParams) error
}

var _ Querier = (*Queries)(nil)
