DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS drivers;
DROP TABLE IF EXISTS fleets;
DROP TYPE IF EXISTS order_status;
DROP TYPE IF EXISTS driver_status;
DROP EXTENSION IF EXISTS "postgis";
DROP EXTENSION IF EXISTS "uuid-ossp";